[postgres]   # main app connection
host = "localhost"
port = 5432
dbname = "postgres"
user = "postgres"
password =  "!Re2300135"

[postgre]   # main app connection
host = "localhost"
port = 5432
dbname = "postgres"
user = "postgres"
password =  "!Re2300138"


