SUPABASE_URL="https://eyjhuatnyozqlxdauqar.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5amh1YXRueW96cWx4ZGF1cWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTcxOTEsImV4cCI6MjA3MTE3MzE5MX0.WmmbawEZcM-j3BTkFx6mCIeQoRHKexxxIJrCTpk-GWw"






